# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjetIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjetIOS
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'GoogleSignIn'
  pod 'BATabBarController', '~> 2.0.0'
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'PubNub', '~> 4'
  pod 'AlamofireImage'



end
